### ISSUE TITLE
Docker如何访问外部数据库

### ISSUE THREAD

**Issue by rafaelchan** [yutiansut/QUANTAXIS#1346]
我在外部已存有数据，未来也打算本地化配置整个QA。所以想在docker里面直接访问外部的本地数据库。在docker内save的时候，也可以保存到外部的数据库。请问一下，如何修改配置文件。

**Comment by yutiansut** [comment]
目前是想考虑基于qaenv项目来统一 或者接入外部环境  

如果你已经有一个外部的mongo 并且知道外部的局域网ip地址  (注意不是127.0.0.1  是局域网 比如192.168.x.x)  你可以直接替换  docker-compose.yaml里面的 环境变量  mgdb为这个ip

**Comment by rafaelchan** [comment]
没有搞明白，请问下面改那部分呢。
 mgdb:
        image: daocloud.io/quantaxis/qamongo_single:latest
        ports:
            - "27017:27017"
        environment:
            - TZ=Asia/Shanghai
            - MONGO_INITDB_DATABASE=quantaxis
        volumes:
            - qamg:/data/db
        networks:
            qanetwork:
                ipv4_address: 172.19.0.2
        restart: always

**Comment by yutiansut** [comment]
不是这个 这个是 mgdb的镜像的结构  他被拉起来的时候 内部可以用 mgdb:27017来访问

你现在是需要连自定义的数据库  所以 你需要修改的是别的镜像的系统变量

例如这个镜像
```
    qa:
        image: daocloud.io/quantaxis/qacommunity:latest
        container_name: qacommunity
        depends_on:
            - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.19.0.3
        ports:
            - "8888:8888"
            - "81:80"
        environment:
          - TZ=Asia/Shanghai
          - LANG=C.UTF-8
          - MONGODB=mgdb
          - QARUN=qaweb
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
        volumes:
            - qacode:/home
        restart: always
```

首先删掉 depends on 里面的依赖项 mgdb

其次 在你的environment里面 把  - MONGODB=mgdb 改成  - MONGODB = '你的mongo服务器所在的局域网地址'


其他镜像以此类推
