### ISSUE TITLE
qa-cron自动更新行情报错，求助～

### ISSUE THREAD

**Issue by LUS8806** [yutiansut/QUANTAXIS#1405]
环境：最新的docker部署的QA
服务器：centOS7
问题：进入qa-cron容器查看日志，发现有错误信息，但不知如何解决，如下图，
![Snip20200122_37](https://user-images.githubusercontent.com/14008897/72870027-f0b79680-3d21-11ea-8cbc-011b4d0ff68d.png)
![Snip20200122_38](https://user-images.githubusercontent.com/14008897/72870024-f0b79680-3d21-11ea-8d2a-4e2c03dcafdf.png)

**Comment by yutiansut** [comment]
咦 docker container重启试试

**Comment by LUS8806** [comment]
```
    qacron:
        image: barretthugh/qa-cron
        environment:
            - MONGODB=mgdb
        restart: always
        
        networks:
            qanetwork:
                ipv4_address: 172.19.0.15
```
在docker-compose文件qacron加上network
这样就解决问题了，谢谢天神
