### ISSUE TITLE
docker部署本机外挂数据库访问不成功

### ISSUE THREAD

**Issue by newlyedward** [yutiansut/QUANTAXIS#1599]
# 问题反馈

## 您使用的QUANTAXIS版本号是什么?

```
1.9.30


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
CPU-Intel(R) Celeron(R) CPU  J3160  @ 1.60GHz  4核
内存-8G
SSD-128G
数据盘-4块4T红盘 raid5




```

## 您的系统环境是什么?
```
- CentOS Linux release 7.3.1611 (Core)
- monodb db version v4.0.7
- Python 3.6.3 :: Anaconda, Inc.
- Docker version 20.10.0, build 7287ab3
```
## 您需要反馈的问题
```
1、使用一键docker部署成功，centos装在ssd上128g，docker缺省目录在/var/lib/dock，只剩50G空间，
save 股票、期货、期权历史数据后，空间耗尽，docker无法运行，停止docker服务，卸载docker

2、重新安装docker，修改/etc/docker/daemon.json文件，将docker缺省目录放置在数据盘

3、修改docker-compose.yaml文件， 数据库和dock儿在同一机器
分别尝试，MONGODB=127.0.0.1
                  MONGODB=192.168.1.111     # 本机固定ip
                  将MONGODB这一行注释掉

4、7个容器有5个运行成功
[root@localhost quantaxis_docker]# docker ps -a
CONTAINER ID   IMAGE                                              COMMAND                  CREATED       STATUS                   PORTS                                                                                                                       NAMES
62814730118a   daocloud.io/quantaxis/qacommunity:latest           "bash /root/run-comm…"   4 hours ago   Up 4 hours               0.0.0.0:8787->8787/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:81->80/tcp                                                          qacommunity
e38d61873f6c   daocloud.io/quantaxis/qarun:latest                 "/root/wait_for_it.s…"   4 hours ago   Up 4 hours               0.0.0.0:8010->8010/tcp                                                                                                      qarun
adf9a9716ca4   daocloud.io/quantaxis/qarealtimecollector:latest   "/root/QUANTAXIS_Rea…"   4 hours ago   **Exited (1)** 4 hours ago                                                                                                                               quantaxis_docker_qamarketcollector_1
55eb040b6acd   daocloud.io/quantaxis/qatrader:latest              "/root/QATrader/dock…"   4 hours ago   **Exited (1)** 4 hours ago                                                                                                                               quantaxis_docker_qatrader_1
a3cb7229e374   daocloud.io/quantaxis/qaeventmq:latest             "docker-entrypoint.s…"   4 hours ago   Up 4 hours               0.0.0.0:4369->4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 0.0.0.0:15672->15672/tcp, 25672/tcp   quantaxis_docker_qaeventmq_1
b0b6cdbd69b7   daocloud.io/quantaxis/qa-monitor:latest            "/bin/sh -c 'python …"   4 hours ago   Up 4 hours               0.0.0.0:61208-61209->61208-61209/tcp                                                                                        quantaxis_docker_qamonitor_1
c0a0a345c321   daocloud.io/quantaxis/qaeditor:latest              "yarn theia start /h…"   4 hours ago   Up 4 hours               0.0.0.0:3001->3000/tcp    
                                                                                                  qaeditor
5、docker logs查看日志，两个容器停止的原因基本一样。
[root@localhost quantaxis_docker]# docker logs 5083c3c28cb4 
wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
wait_for_it.sh: timeout occurred after waiting 15 seconds for qaeventmq:5672
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QASetting.py", line 99, in get_config
    return config.get(section, option)
                                                       中间异常部分省略
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

6、15672的RabbitMQ 61208的monitor 8888的jupyterlab都能成功访问
jupyterlab的终端可以使用quantaxis不涉及数据库的操作

7.、本机使用mongo 访问数据库，其他机器使用Robo 3T 均能成功访问数据库。

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
QQ：504959142
```

THANKS
by yutiansut
2017.12

**Comment by newlyedward** [comment]
今天直接在centos上部署QUANTAXIS没有问题，数据存储成功，docker部署还是不成功。

**Comment by manyhelp** [comment]
1.本地设置mongodb，测试192.168.1.X 连接你的mongodb。（如使用Navicat连接）
2.修改  docker-compose.yaml  如下，里面192.168.1.6 是你的机器IP
`version: '2'
services:
    qa:
        image: daocloud.io/quantaxis/qacommunity:latest
        container_name: qacommunity
        depends_on:
           # - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.19.0.3
        ports:
            - "8888:8888"
            - "81:80"
            - "8787:8787"
        environment:
          - TZ=Asia/Shanghai
          - LANG=C.UTF-8
          - MONGODB=192.168.1.6
          - QARUN=qaweb
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
        volumes:
            - qacode:/root/code
        restart: always

    # qacron:
    #     image: daocloud.io/quantaxis/qa-cron:latest
    #     environment:
    #         - MONGODB=mgdb
    #     restart: always

    qaweb_run:
        image: daocloud.io/quantaxis/qarun:latest
        container_name: qarun
        depends_on:
           # - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.19.0.4
        ports:
            - "8010:8010"
        environment:
          - MONGODB=192.168.1.6
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
          - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
          - TZ=Asia/Shanghai
        restart: always
        depends_on:
          - qaeventmq
         # - mgdb
        command: ['/root/wait_for_it.sh', 'qaeventmq:5672', '--' , "/root/runcelery.sh"]


    # mgdb:
    #     image: daocloud.io/quantaxis/qamongo_single:latest
    #     ports:
    #         - "27017:27017"
    #     environment:
    #         - TZ=Asia/Shanghai
    #         - MONGO_INITDB_DATABASE=quantaxis
    #     volumes:
    #         - qamg:/data/db
    #     networks:
    #         qanetwork:
    #             ipv4_address: 172.19.0.2
    #     restart: always


    qaeventmq:
        image: daocloud.io/quantaxis/qaeventmq:latest
        ports:
            - "15672:15672"
            - "5672:5672"
            - "4369:4369"
        environment:
            - TZ=Asia/Shanghai
        networks:
            qanetwork:
                ipv4_address: 172.19.0.5
        restart: always

    qamonitor:
        image: daocloud.io/quantaxis/qa-monitor:latest
        ports:
            - "61209:61209"
            - "61208:61208"
        pid: 'host'
        networks:
            qanetwork:
                ipv4_address: 172.19.0.6

        restart: always

    qamarketcollector:
        image: daocloud.io/quantaxis/qarealtimecollector:latest
        ports:
            - "8011:8011"
        depends_on:
          #  - mgdb
            - qaeventmq
        environment:
            - MONGODB=192.168.1.6
            - EventMQ_IP=qaeventmq
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - QARUN=qaweb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
        networks:
            qanetwork:
                ipv4_address: 172.19.0.8
        command:
            ['/root/QUANTAXIS_RealtimeCollector/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'/root/QUANTAXIS_RealtimeCollector/docker/start_collector.sh']

    qatrader:
        image: daocloud.io/quantaxis/qatrader:latest
        ports:
            - "8020:8020"
        depends_on:
          #  - mgdb
            - qaeventmq
        environment:
            - MONGODB=192.168.1.6
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
            - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
            - TZ=Asia/Shanghai
        command:
            ['/root/QATrader/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'qatraderserver']

        networks:
            qanetwork:
                ipv4_address: 172.19.0.9

    editer:
        image: daocloud.io/quantaxis/qaeditor:latest
        container_name: qaeditor
        networks: 
            qanetwork:
                ipv4_address: 172.19.0.14
        ports: 
            - "3001:3000"
        environment:
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - MONGODB=192.168.1.6
            - QARUN=qaweb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
        restart: always
        volumes: 
            - qacode:/home/project


volumes:
    # qamg:
    #     external:
    #         name: qamg
    qacode:
        external:
            name: qacode
networks:
    qanetwork:
        ipam:
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1
`

**Comment by newlyedward** [comment]
分别尝试，MONGODB=127.0.0.1
                  MONGODB=192.168.1.111     # 本机固定ip
                  将MONGODB这一行注释掉
三种修改方法都不行，mongo我一直再用，直接部署quantaxis也可以使用。
```
version: "2"
services:
    qa:
        image: daocloud.io/quantaxis/qacommunity:latest
        container_name: qacommunity
        depends_on:
#            - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.19.0.3
        ports:
            - "8888:8888"
            - "81:80"
            - "8787:8787"
        environment:
          - TZ=Asia/Shanghai
          - LANG=C.UTF-8
          - MONGODB=127.0.0.1
          - QARUN=qaweb
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
        volumes:
            - qacode:/root/code
        restart: always

    # qacron:
    #     image: daocloud.io/quantaxis/qa-cron:latest
    #     environment:
    #         - MONGODB=192.168.2.88
    #     restart: always

    qaweb_run:
        image: daocloud.io/quantaxis/qarun:latest
        container_name: qarun
        depends_on:
#            - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.19.0.4
        ports:
            - "8010:8010"
        environment:
          - MONGODB=127.0.0.1
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
          - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
          - TZ=Asia/Shanghai
        restart: always
        command: ['/root/wait_for_it.sh', 'qaeventmq:5672', '--' , "/root/runcelery.sh"]


#    mgdb:
#        image: daocloud.io/quantaxis/qamongo_single:latest
#        ports:
#            - "27017:27017"
#        environment:
#            - TZ=Asia/Shanghai
#            - MONGO_INITDB_DATABASE=quantaxis
#        volumes:
#            - qamg:/data/db
#        networks:
#            qanetwork:
#                ipv4_address: 172.19.0.2
#        restart: always


    qaeventmq:
        image: daocloud.io/quantaxis/qaeventmq:latest
        ports:
            - "15672:15672"
            - "5672:5672"
            - "4369:4369"
        environment:
            - TZ=Asia/Shanghai
        networks:
            qanetwork:
                ipv4_address: 172.19.0.5
        restart: always

    qamonitor:
        image: daocloud.io/quantaxis/qa-monitor:latest
        ports:
            - "61209:61209"
            - "61208:61208"
        pid: "host"
        networks:
            qanetwork:
                ipv4_address: 172.19.0.6

        restart: always

    qamarketcollector:
        image: daocloud.io/quantaxis/qarealtimecollector:latest
        ports:
            - "8011:8011"
        depends_on:
#            - mgdb
            - qaeventmq
        environment:
            - MONGODB=127.0.0.1
            - EventMQ_IP=qaeventmq
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - QARUN=qaweb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
        networks:
            qanetwork:
                ipv4_address: 172.19.0.8
        command:
            ['/root/QUANTAXIS_RealtimeCollector/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'/root/QUANTAXIS_RealtimeCollector/docker/start_collector.sh']


    qatrader:
        image: daocloud.io/quantaxis/qatrader:latest
        ports:
            - "8020:8020"
        depends_on:
#            - mgdb
            - qaeventmq
        environment:
            - MONGODB=127.0.0.1
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
            - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
            - TZ=Asia/Shanghai
        command:
            ['/root/QATrader/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'qatraderserver']

        networks:
            qanetwork:
                ipv4_address: 172.19.0.9

    editer:
        image: daocloud.io/quantaxis/qaeditor:latest
        container_name: qaeditor
        networks:
            qanetwork:
                ipv4_address: 172.19.0.14
        ports:
            - "3001:3000"
        environment:
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - MONGODB=127.0.0.1
            - QARUN=qaweb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
        restart: always
        volumes:
            - qacode:/home/project


volumes:
#    qamg:
#        external:
#            name: qamg
    qacode:
        external:
            name: qacode
networks:
    qanetwork:
        ipam:
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1

```
